tee-supplicant: add CFG_TEE_SUPP_PLUGINS to enable or not plugin support
This change allows optee_client configuration to enable or not supplicant
plugin support. The feature is enabled from switch CFG_TEE_SUPP_PLUGINS.
The configuration is default enable for backward compatibility purpose.

There are OSes where TEE supplicant plugin cannot be supported for
example when the OS does not enable dynamic/shared libraries. Such
systems should still be able to embed OP-TEE assuming the supplicant
plugin support is not embedded. Prior this change was optee_client
failing to build for such systems with a error message like the one
below reported by Buildroot CI build [1]:

/tmp/instance-2/output-1/build/optee-client-3.13.0/tee-supplicant/src/plugin.c:8:10: fatal error: dlfcn.h: No such file or directory
    8 | #include <dlfcn.h>
      |          ^~~~~~~~~

Link: [1] http://autobuild.buildroot.net/results/56d1ec172d0d857d6a968397b7785f961fad1043/
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jerome Forissier <jerome@forissier.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>